import type { Metadata } from "next";
import { Onest } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/src/components/Footer";
import Header from "@/src/components/Header";
import StyledMantaineProvider from "@/src/providers/StyledMantaineProvider";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin", "latin-ext", "cyrillic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const benzin = localFont({
  src: "../public/fonts/Benzin-Semibold.woff2",
  variable: "--font-benzin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} ${benzin.variable} antialiased`}>
        <StyledMantaineProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </StyledMantaineProvider>
      </body>
    </html>
  );
}
